### ISSUE TITLE
Remove *ALL* of HTML tags from markdown files

### ISSUE THREAD

**Issue by minacle** [bayoen/bayoen.github.io#1]

**Comment by semir4in** [comment]
There's no substitute for html..... What should I do to realize things already existing without html?

**Comment by minacle** [comment]
@semir4in

`<b>bold</b>` or `<strong>bold</strong>` can be `**bold**` or `__bold__`.

`<i>italic</i>` can be `*italic*` oe `_italic_`.

Headers like `<h1>title</h1>` and `<h2>subtitle</h2>` can be `# title` and `## subtitle` and so on.

`<a href="file.ext">link</a>` can be `[link](file.ext)`.

`<img src="image.png" alt="describing image">` can be `![describing image](image.png)`.

To details, you can read [the reference page](https://kramdown.gettalong.org/quickref.html) of [kramdown](https://kramdown.gettalong.org), which is Github Pages using, or [the mastering markdown guide](https://guides.github.com/features/mastering-markdown/) by Github.

**Comment by semir4in** [comment]
I totally agree with you. Markdown `_italic_` and `**bold**` are super good!

As you can see from [here](https://raw.githubusercontent.com/bayoen/bayoen.github.io/master/star/en/guide.md), I used both markdown and html and I had to use the combination codes.

At first, I tried some other ways but I can not find fancy markdown setting to do that. So I read markdown guide and some stackoverflow articles. They said that the ability to like center images or text could not be implemented using only markdowns. That is the reason that I can not change all html codes into markdown T_T

Can I realize those functions (centering or inline link) in class with only markdown grammar? I hope there's a way to modify the markdown preset or something T_T...

**Comment by minacle** [comment]
You can use an HTML tag for aligning, styling or etc. But this time, I want to edit CSS (or SCSS or something..) directly.

Links are very simple. If you write `[This is __*AWESOME*__ Link!!](https://example.com)`, it becomes `<a href="https://example.com">This is <b><i>AWESOME</i></b> Link!!</a>`. It rendered like this: [This is __*AWESOME*__ Link!!](https://example.com)

You can embed any contents some images into link title.

And `<br>` is equals to trailing double whitespace characters, `  `.

**Comment by semir4in** [comment]
ops.. I meant **inline link for table of contents**. Text alignment is still problem with markdown T_T

**Comment by minacle** [comment]
`[Link](#id)` is the way to link to an ID for header. You can set an ID like [this](https://kramdown.gettalong.org/syntax.html#specifying-a-header-id).

Table alignments:

```
| Left alignment | Centre alignment | Right alignment | Default alignment |
|:--- |:---:| ---:| --- |
| Alice | Bob | Carlos | David |
```

becomes

| Left alignment | Centre alignment | Right alignment | Default alignment |
|:--- |:---:| ---:| --- |
| Alice | Bob | Carlos | David |
